"""Add area and other fields to PredictionHistory

Revision ID: 56eab1275289
Revises: 
Create Date: 2025-06-18 16:37:37.758022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56eab1275289'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('furnished', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('result', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('prediction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prediction', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('result')
        batch_op.drop_column('city')
        batch_op.drop_column('furnished')
        batch_op.drop_column('rooms')
        batch_op.drop_column('area')

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
