"""Added is_public to User

Revision ID: 9f163b50b97a
Revises: 56eab1275289
Create Date: 2025-06-19 00:21:54.516016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f163b50b97a'
down_revision = '56eab1275289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.alter_column('area',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('rooms',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('furnished',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('result',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    with op.batch_alter_table('prediction_history', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('furnished',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rooms',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('area',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
